<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="1152" started-at="2012-09-20T22:35:30Z" finished-at="2012-09-20T22:35:31Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="1152" started-at="2012-09-20T22:35:30Z" finished-at="2012-09-20T22:35:31Z">
      <class name="cn.com.carit.platform.service.AccountServiceTestCase">
        <test-method status="FAIL" signature="testLogon()[pri:0, instance:cn.com.carit.platform.service.AccountServiceTestCase@2adb1d4]" name="testLogon" duration-ms="1128" started-at="2012-09-20T22:35:30Z" finished-at="2012-09-20T22:35:31Z">
          <exception class="org.springframework.web.client.HttpClientErrorException">
            <message>
              <![CDATA[404 Not Found]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.springframework.web.client.HttpClientErrorException: 404 Not Found
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:76)
	at org.springframework.web.client.RestTemplate.handleResponseError(RestTemplate.java:486)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:443)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:401)
	at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:279)
	at com.rop.client.DefaultRopClient$DefaultClientRequest.post(DefaultRopClient.java:239)
	at com.rop.client.DefaultRopClient$DefaultClientRequest.post(DefaultRopClient.java:235)
	at cn.com.carit.platform.RopTestCaseClient.logon(RopTestCaseClient.java:51)
	at cn.com.carit.platform.service.AccountServiceTestCase.testLogon(AccountServiceTestCase.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- org.springframework.web.client.HttpClientErrorException -->
        </test-method> <!-- testLogon -->
      </class> <!-- cn.com.carit.platform.service.AccountServiceTestCase -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
